# Generated by Django 3.2.8 on 2021-10-23 23:13

from django.db import migrations, models
import myproject.myapp.base.BaseModel


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210425_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeModel',
            fields=[
                ('youtube_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('youtube_title', models.CharField(max_length=200)),
                ('youtube_date', models.DateTimeField(auto_now=True, help_text='video request date')),
                ('youtube_tags', models.CharField(max_length=200)),
            ],
            bases=(models.Model, myproject.myapp.base.BaseModel.BaseModelProtocol),
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
        migrations.DeleteModel(
            name='DiaryModel',
        ),
        migrations.DeleteModel(
            name='LifeEvent',
        ),
        migrations.DeleteModel(
            name='TodoTask',
        ),
    ]
