# Generated by Django 3.2 on 2021-04-27 00:46

from django.db import migrations, models
import myproject.myapp.features.Analytics.protocol.AnalyticProtocol


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_auto_20210425_0135"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetModel",
            fields=[
                ("budget_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "budget_title",
                    models.CharField(max_length=6000, verbose_name="budget title"),
                ),
                (
                    "budge_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="budget Date"),
                ),
                ("budget_amount", models.FloatField(verbose_name="budget Amount")),
            ],
            bases=(
                models.Model,
                myproject.myapp.features.Analytics.protocol.AnalyticProtocol.AnalyticProtocol,
            ),
        ),
    ]
